### ISSUE TITLE
Footer content

### ISSUE THREAD

**Issue by mrodriguez3313** [alancastilleja/SiteProject#29]
Im thinking we could have either three columns:  

- title=National 
     - content = national orgs, national donate, national petitions. 
- col 2 title = States
    - content = states-we-have-currently. 
- col 3 title=About
    - content = about developers, how we source information, how we built the site?

or we have 4 columns were we have the titles be:

- col 1 title =  Orgs
    - content = cali_orgs, texas_org, MN_org, etc.
- col 2 title = donate
    - content = cali_donate, texas_donate, MN_donate, etc.
- col 3 title = Businesses
    - content = calibiz, texbiz, MNbiz, etc.
- col 4 title = About
    - content = About, Developers, something else

**Comment by alancastilleja** [comment]
Depends how we want to think about this. Do we want people to stay on the site as long as possible or do we want them to quickly get the information they need? Quick info: 2nd option, More time on site: 1st option. I am cool with the second one over the first.
