### ISSUE TITLE
Make Navbar consistent through all webpages.

### ISSUE THREAD

**Issue by mrodriguez3313** [alancastilleja/SiteProject#8]
Make the tool bar its own file to import with jinja to the other files. So to not continue to repeat code for every potential new webpage we make and making the current pages we have.

**Comment by alancastilleja** [comment]
The toolbar? You mean the navbar? and sure that works.

**Comment by mrodriguez3313** [comment]
Yeah I meant the navbar sorry

**Comment by mrodriguez3313** [comment]
I think this issue is good to close.
