### ISSUE TITLE
Make footer consistent through all webpages.

### ISSUE THREAD

**Issue by mrodriguez3313** [alancastilleja/SiteProject#9]
Same thing as the header/toolbar, make the footer its own component to import to all other pages so that we don't have to rewrite code.

**Comment by alancastilleja** [comment]
should we make them separate? Because I had an idea of how we would implement base files. The index page will have its own base html file while the states have their own and so do the national links.

**Comment by mrodriguez3313** [comment]
What ever will make it easier. I was coming from React, where every little thing is like individualized into files and then just imported and exported into other files. But since you know the flask way to do things Ill let you take the lead on these.

**Comment by mrodriguez3313** [comment]
Do you think we can close these issues. I think theyre good now?
